### ISSUE TITLE
Features not responding

### ISSUE THREAD

**Issue by StripedBanana** [mlajtos/moniel#10]
So basically whenever I hit `Sketch` > `Open`, `Save as` or `New` it's not doing anything at all. I can use `Save` and it will actually save a `.pdf` and `.svg` screenshot of the app in the `sketches` folder.

PS: the `.svg` file looks good when I open it on Chrome but not on IE or Gimp (all objects but arrows and some boxes are stuck on the top left)

**Comment by mlajtos** [comment]
All menu items in Sketch menu should work now. Also SVG should be more compatible, but text on nodes is probably still a bit off. I can't test it because I don't have access to Gimp or IE.

**Comment by StripedBanana** [comment]
By the way I cannot do `npm install` anymore. I just cloned a minute ago.

```
~/Documents/moniel$ npm --version
1.3.10

~/Documents/moniel$ npm install
npm http GET https://registry.npmjs.org/electron-devtools-installer
npm http GET https://registry.npmjs.org/dagre
npm http GET https://registry.npmjs.org/d3
npm http GET https://registry.npmjs.org/color-hash
npm http GET https://registry.npmjs.org/graphlib
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/ohm-js
npm http GET https://registry.npmjs.org/react
npm http GET https://registry.npmjs.org/react-dom
npm http GET https://registry.npmjs.org/ace-moniel-builds
npm http GET https://registry.npmjs.org/fira-code
npm http GET https://registry.npmjs.org/string-pixel-width
npm http GET https://registry.npmjs.org/babel-cli
npm http GET https://registry.npmjs.org/babel-plugin-transform-class-properties
npm http GET https://registry.npmjs.org/babel-plugin-transform-object-rest-spread
npm http GET https://registry.npmjs.org/babel-preset-es2017
npm http GET https://registry.npmjs.org/babel-preset-latest
npm http GET https://registry.npmjs.org/babel-preset-react
npm http GET https://registry.npmjs.org/electron
npm http GET https://registry.npmjs.org/electron-reload
npm http GET https://registry.npmjs.org/electron-packager
npm http GET https://registry.npmjs.org/node-sass
npm http 304 https://registry.npmjs.org/dagre
npm http 304 https://registry.npmjs.org/graphlib
npm http 304 https://registry.npmjs.org/d3
npm http 304 https://registry.npmjs.org/color-hash
npm http 304 https://registry.npmjs.org/electron-devtools-installer
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/jquery
npm http 304 https://registry.npmjs.org/react-dom
npm http 304 https://registry.npmjs.org/ohm-js
npm http 304 https://registry.npmjs.org/react
npm http 304 https://registry.npmjs.org/string-pixel-width
npm http 304 https://registry.npmjs.org/babel-plugin-transform-object-rest-spread
npm http 304 https://registry.npmjs.org/babel-plugin-transform-class-properties
npm http 304 https://registry.npmjs.org/babel-preset-es2017
npm http 304 https://registry.npmjs.org/babel-cli
npm http 304 https://registry.npmjs.org/electron
npm http 304 https://registry.npmjs.org/babel-preset-latest
npm http 304 https://registry.npmjs.org/babel-preset-react
npm http 304 https://registry.npmjs.org/node-sass
npm http 304 https://registry.npmjs.org/electron-reload
npm http 404 https://registry.npmjs.org/ace-moniel-builds
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.4.0+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/jnamdarirani/Documents/moniel
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 304 https://registry.npmjs.org/electron-packager
npm http 404 https://registry.npmjs.org/fira-code
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.4.0+
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/jnamdarirani/Documents/moniel
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jnamdarirani/Documents/moniel/npm-debug.log
npm ERR! not ok code 0
```

**Comment by mlajtos** [comment]
And it worked before?

NPM tries to download private packages from npmjs.org registry which is wrong.

Is package.json without any changes?

I successfully tested Node 0.10.48 with NPM 2.15.1 – that were the oldest packages my system provided.

Can you upgrade your system?

**Comment by mlajtos** [comment]
I am closing this issue. Please open a new one if you still have a problem.
